name: sampleproject
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path_provider: ^2.0.10
  flutter:
    sdk: flutter
  
  provider: ^4.1.2
  

  cupertino_icons: ^1.0.0

  # scan QR Code
  flutter_barcode_scanner: ^1.0.1

  # create QR Code
  barcode_widget: ^1.5.0
  
  intl: ^0.17.0

  http: ^0.13.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.9.2"
  
  



flutter_icons:
  android: true
  image_path: "assets/bike.png" 

flutter:
  uses-material-design: true